repo: src/third_party/icu
patches:
-
  author: Ales Pergl <alpergl@microsoft.com>
  file: build_gn.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: no_inline_default_constructor.patch
  description: null
